version: '2'
services:
  api-gateway:
    image: lint-microservice:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.test
    command: ["yarn" , "start:dev"]
     
  user-service:
    image: lint-microservice:latest
    ports:
      - "5006:5006"
    env_file:
      - .env.test
    command: ["yarn" , "start:dev", "user"]
    
  auth-service:
    image: lint-microservice:latest
    ports:
      - "5001:5001"
    env_file:
      - .env.test
    command: ["yarn" , "start:dev", "auth"]
    
  relationship-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - .env.test
    command: ["yarn" , "start:dev", "relationship"]
    

  post-service:
    image: lint-microservice:latest
    ports:
      - "5003:5003"
    env_file:
      - .env.test
    command: ["yarn" , "start:dev", "post"]
    

  interaction-service:
    image: lint-microservice:latest
    ports:
      - "5004:5004"
    env_file:
      - .env.test
    command: ["yarn" , "start:dev", "interaction"]
    

  notification-service:
    image: lint-microservice:latest
    ports:
      - "5005:5005"
      - "3001:3001"
    env_file:
      - .env.test
    command: ["yarn" , "start:dev", "notification"]
    

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock