// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.26.0
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface SigninRequest {
  email: string;
  password: string;
}

export interface Token {
  token: string;
  type: string;
  refreshToken: string;
  issuedAt: string;
  expireAt: string;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  signin(request: SigninRequest): Observable<Token>;

  refreshToken(request: RefreshTokenRequest): Observable<Token>;
}

export interface AuthServiceController {
  signin(request: SigninRequest): Promise<Token> | Observable<Token> | Token;

  refreshToken(request: RefreshTokenRequest): Promise<Token> | Observable<Token> | Token;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["signin", "refreshToken"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
