// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.26.0
// source: count.proto

/* eslint-disable */

export const protobufPackage = "";

export interface Count {
  count: number;
}

export const _PACKAGE_NAME = "";
