// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.2
// source: empty.proto

/* eslint-disable */

export const protobufPackage = "";

export interface Empty {
}

export const _PACKAGE_NAME = "";
