// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.26.0
// source: query.proto

/* eslint-disable */

export const protobufPackage = '';

export enum SortOrder {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export interface SearchParams {
  key?: string | undefined;
  skip?: number | undefined;
  take?: number | undefined;
  tags?: string[];
}

export interface StringFilter {
  equals?: string | undefined;
  in?: string[];
  notIn?: string[];
  lt?: string | undefined;
  lte?: string | undefined;
  gt?: string | undefined;
  gte?: string | undefined;
  contains?: string | undefined;
  startsWith?: string | undefined;
  endsWith?: string | undefined;
}

export interface IntFilter {
  equals?: number | undefined;
  in: number[];
  notIn: number[];
  lt?: number | undefined;
  lte?: number | undefined;
  gt?: number | undefined;
  gte?: number | undefined;
}

export interface DateTimeFilter {
  equals?: string | undefined;
  in: string[];
  notIn: string[];
  lt?: string | undefined;
  lte?: string | undefined;
  gt?: string | undefined;
  gte?: string | undefined;
}

export const _PACKAGE_NAME = '';
